"""Added twitter_id column to User table

Revision ID: 2b30072a0e79
Revises: a4cad9f95ab5
Create Date: 2021-05-19 11:45:54.499045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b30072a0e79'
down_revision = 'a4cad9f95ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('twitter_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['twitter_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'twitter_id')
    # ### end Alembic commands ###
